x = 0
pins.i2c_write_number(112, 0, NumberFormat.UINT8_BE, False)
control.wait_micros(50)
pins.i2c_write_number(112, 1 << 2, NumberFormat.UINT8_BE, False)
control.wait_micros(50)
Rangefinder.init()
pins.i2c_write_number(112, 1 << 3, NumberFormat.UINT8_BE, False)
control.wait_micros(50)
Rangefinder.init()
pins.i2c_write_number(112, 1 << 4, NumberFormat.UINT8_BE, False)
control.wait_micros(50)
Rangefinder.init()

def on_forever():
    global x
    serial.write_string("" + ("----\r\n"))
    pins.i2c_write_number(112, 0, NumberFormat.UINT8_BE, False)
    control.wait_micros(50)
    serial.write_string("start of loop" + str(control.millis()) + "\r\n")
    pins.i2c_write_number(112, 1 << 2, NumberFormat.UINT8_BE, False)
    control.wait_micros(50)
    x = x + Rangefinder.distance()
    serial.write_string("ToF 2:" + str(control.millis()) + "\r\n")
    pins.i2c_write_number(112, 1 << 3, NumberFormat.UINT8_BE, False)
    control.wait_micros(50)
    x = x + Rangefinder.distance()
    serial.write_string("ToF 3:" + str(control.millis()) + "\r\n")
    pins.i2c_write_number(112, 1 << 4, NumberFormat.UINT8_BE, False)
    control.wait_micros(50)
    x = x + Rangefinder.distance()
    serial.write_string("ToF 4:" + str(control.millis()) + "\r\n")
    led.plot_bar_graph(x, 1500)
    serial.write_string("end of plotBarGraph:" + str(control.millis()) + "\r\n")
    basic.pause(1000)
basic.forever(on_forever)
